### ISSUE TITLE
BLS_BLS12381 is not supported

### ISSUE THREAD

**Issue by nozim** [onflow/crypto#2]
### Current Behavior

```
_, err := crypto.GeneratePrivateKey(crypto.BLSBLS12381, []byte("111"))
log.Println(err == nil) // returns false 
```

### Expected Behavior

```
_, err := crypto.GeneratePrivateKey(crypto.BLSBLS12381, []byte("111"))
log.Println(err == nil) // should return true
```

### Steps To Reproduce

```
package main

import (
	"log"

	"github.com/onflow/flow-go/crypto"
)

func main() {
	_, err := crypto.GeneratePrivateKey(crypto.BLSBLS12381, []byte("111"))
	log.Println(err)
}
```

### Environment

```markdown
Go version go1.19
```

**Comment by nozim** [comment]
I'm working on flow-go and most of unit tests locally fail because of this

**Comment by tarakby** [comment]
Hi @nozim,
- the build or test command has to include a `relic` tag, I suspect this is the issue. For instance `go build -tags=relic main.go`. This includes the Relic library in the build (which is required to build BLS stuff). 
- note that before the build/test, you would need to setup that relic library by calling `make crypto_setup_gopath` (it's mentioned in the [readme](https://github.com/onflow/flow-go#installation))
- FYI, we are working on removing the pre-build step and the build tag. They should be removed in a few months.

**Comment by tarakby** [comment]
Btw, you would still get an error in your example after executing the steps properly because the seed `[]byte("111")` is too short :)

**Comment by nozim** [comment]
@tarakby https://github.com/onflow/crypto/blob/ba450063f1cc9ea5c6b845e765e66fb374965500/sign.go#L70 this line kind of disagrees with you ;)

**Comment by tarakby** [comment]
Once you use `-tags=relic` this [file](https://github.com/onflow/crypto/blob/main/sign_relic.go) is built (thanks to lines 1 and 2). And then it's this [function](https://github.com/onflow/crypto/blob/main/sign_relic.go#L29) that is called. You can see that BLS is used there.

Have you followed the steps [here](https://github.com/onflow/crypto/issues/2#issuecomment-1654184760) and still had an issue?

**Comment by nozim** [comment]
yes, in the process.Sorry previous comment was premature :pray:

**Comment by nozim** [comment]
@tarakby tests are running smooth. Thank you very much for detailed instruction. Closing the ticket.
