### ISSUE TITLE
Update docs: clarify library usage

### ISSUE THREAD

**Issue by bartolomej** [onflow/crypto#7]
### Current Behavior

As someone who isn't that familiar with Go, it wasn't super clear to me how to use this library when importing it in Go code or when using it indirectly (e.g. when using flow-go - which was the case for me).

It also seemed weird that I flow-go docs didn't mention anything about the required build/setup steps I should take before consuming flow-go lib and building my Go program.

### Expected Behavior

- clarify library usage docs
- add docs to dependant library repos

Relevant Discord discussion: https://discord.com/channels/613813861610684416/1222484856043343942

### Steps To Reproduce

N/A

### Environment

```markdown
N/A
```

**Comment by tarakby** [comment]
github.com/onflow/crypto/pull/6 clarifies the build a bit further. Feel free to comment on the PR directly if you think some details aren't clear. 

I'll also add a link to the crypto build section in the other repos like `flow-go`.
